import {IoShareSocialSharp} from "react-icons/io5";


const routesConfig = [
  {
    id: 'app',
    title: 'Sample',
    messageId: 'sidebar.sample',
    type: 'group',
    children: [

      {
        id: 'social',
        title: 'social',
        messageId: 'sidebar.sample.social',
        type: 'item',
        icon: <IoShareSocialSharp />,
        path: '/social',
      },
      {
        id: 'about',
        title: 'about',
        messageId: 'sidebar.sample.about',
        type: 'item',
        icon: <IoShareSocialSharp />,
        path: '/about',
      },
      {
        id: 'contact',
        title: 'contact',
        messageId: 'sidebar.sample.contact',
        type: 'item',
        icon: <IoShareSocialSharp />,
        path: '/contact',
      },
      {
        id: 'creadit',
        title: 'creadit',
        messageId: 'sidebar.sample.creadit',
        type: 'item',
        icon: <IoShareSocialSharp />,
        path: '/creadit',
      },
      {
        id: 'banner',
        title: 'banner',
        messageId: 'sidebar.sample.banner',
        type: 'item',
        icon: <IoShareSocialSharp />,
        path: '/banner',
      },
      {
        id: 'insurance',
        title: 'insurance',
        messageId: 'sidebar.sample.insurance',
        type: 'item',
        icon: <IoShareSocialSharp />,
        path: '/insurance',
      },
      {
        id: 'map',
        title: 'map',
        messageId: 'sidebar.sample.map',
        type: 'item',
        icon: <IoShareSocialSharp />,
        path: '/map',
      },
      {
        id: 'news',
        title: 'news',
        messageId: 'sidebar.sample.news',
        type: 'item',
        icon: <IoShareSocialSharp />,
        path: '/news',
      },
      {
        id: 'service',
        title: 'service',
        messageId: 'sidebar.sample.service',
        type: 'item',
        icon: <IoShareSocialSharp />,
        path: '/service',
      },
      {
        id: 'types',
        title: 'types',
        messageId: 'sidebar.sample.types',
        type: 'item',
        icon: <IoShareSocialSharp />,
        path: '/types',
      },
      {
        id: 'countries',
        title: 'countries',
        messageId: 'sidebar.sample.countries',
        type: 'item',
        icon: <IoShareSocialSharp />,
        path: '/countries',
      },
      {
        id: 'brands',
        title: 'brands',
        messageId: 'sidebar.sample.brands',
        type: 'item',
        icon: <IoShareSocialSharp />,
        path: '/brands',
      },
      {
        id: 'car',
        title: 'car',
        messageId: 'sidebar.sample.car',
        type: 'item',
        icon: <IoShareSocialSharp />,
        path: '/car',
      },
    ],
  },
];
export default routesConfig;
